# TEXT PROCESSING ----- STEP: 1 -----> CLEANING INPUT

# TOKENIZATION:

#shortcuts used: 
esc+m - markdown
esc+y - code


To install Natural language tool kit: (directly)

In [1]:
!pip install nltk

In [2]:
corpus="""Emma wakes up at 7 AM and prepares a cup of coffee before heading to work. \n The weather is cloudy today, but she enjoys the cool breeze on her way. At the office, she emails her manager: 'Could we schedule a meeting for tomorrow at 10 AM?' Her colleague, Jake, asks, 'Do you need help with the report?' \n She replies, 'Yes, that would be great!' During lunch, she reads a news article titled 'New AI Breakthroughs in Healthcare.' Later, her phone buzzes with a notification: 'Flash Sale – 50% off on electronics!' After work, she stops by the grocery store to buy fresh vegetables and bread. At home, she watches a documentary about wildlife conservation. Before sleeping, she sets an alarm for 6 AM and plans her tasks for the next day."""


In [3]:
corpus
#this prints along with quotes(") and new line(\n)

"Emma wakes up at 7 AM and prepares a cup of coffee before heading to work. \n The weather is cloudy today, but she enjoys the cool breeze on her way. At the office, she emails her manager: 'Could we schedule a meeting for tomorrow at 10 AM?' Her colleague, Jake, asks, 'Do you need help with the report?' \n She replies, 'Yes, that would be great!' During lunch, she reads a news article titled 'New AI Breakthroughs in Healthcare.' Later, her phone buzzes with a notification: 'Flash Sale – 50% off on electronics!' After work, she stops by the grocery store to buy fresh vegetables and bread. At home, she watches a documentary about wildlife conservation. Before sleeping, she sets an alarm for 6 AM and plans her tasks for the next day."

In [4]:
print(corpus)

Emma wakes up at 7 AM and prepares a cup of coffee before heading to work. 
 The weather is cloudy today, but she enjoys the cool breeze on her way. At the office, she emails her manager: 'Could we schedule a meeting for tomorrow at 10 AM?' Her colleague, Jake, asks, 'Do you need help with the report?' 
 She replies, 'Yes, that would be great!' During lunch, she reads a news article titled 'New AI Breakthroughs in Healthcare.' Later, her phone buzzes with a notification: 'Flash Sale – 50% off on electronics!' After work, she stops by the grocery store to buy fresh vegetables and bread. At home, she watches a documentary about wildlife conservation. Before sleeping, she sets an alarm for 6 AM and plans her tasks for the next day.


## Converting Corpus to documents:

In [5]:
import nltk
from nltk.tokenize import sent_tokenize
# sent_tokenize trys to convert corpus to documents.

In [6]:
nltk.download('punkt')
nltk.download('punkt_tab')
#downloaded to obtain the resource—to load english pickle file

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [7]:
documents=sent_tokenize(corpus)
sentences= sent_tokenize(corpus)

In [8]:
print(documents)
print(sentences)

['Emma wakes up at 7 AM and prepares a cup of coffee before heading to work.', 'The weather is cloudy today, but she enjoys the cool breeze on her way.', "At the office, she emails her manager: 'Could we schedule a meeting for tomorrow at 10 AM?'", "Her colleague, Jake, asks, 'Do you need help with the report?'", "She replies, 'Yes, that would be great!'", "During lunch, she reads a news article titled 'New AI Breakthroughs in Healthcare.'", "Later, her phone buzzes with a notification: 'Flash Sale – 50% off on electronics!'", 'After work, she stops by the grocery store to buy fresh vegetables and bread.', 'At home, she watches a documentary about wildlife conservation.', 'Before sleeping, she sets an alarm for 6 AM and plans her tasks for the next day.']
['Emma wakes up at 7 AM and prepares a cup of coffee before heading to work.', 'The weather is cloudy today, but she enjoys the cool breeze on her way.', "At the office, she emails her manager: 'Could we schedule a meeting for tomorro

In [9]:
#now documents has all the sentences divide by ., \n and !.
type(documents)

list

In [10]:
#To iterate through sentences:
for sentence in documents:
    print(sentence)
#to prints as a string not as a list.

Emma wakes up at 7 AM and prepares a cup of coffee before heading to work.
The weather is cloudy today, but she enjoys the cool breeze on her way.
At the office, she emails her manager: 'Could we schedule a meeting for tomorrow at 10 AM?'
Her colleague, Jake, asks, 'Do you need help with the report?'
She replies, 'Yes, that would be great!'
During lunch, she reads a news article titled 'New AI Breakthroughs in Healthcare.'
Later, her phone buzzes with a notification: 'Flash Sale – 50% off on electronics!'
After work, she stops by the grocery store to buy fresh vegetables and bread.
At home, she watches a documentary about wildlife conservation.
Before sleeping, she sets an alarm for 6 AM and plans her tasks for the next day.


## Converting corpus & Documents to Words:

In [11]:
from nltk.tokenize import word_tokenize
#to convert corpus and documents to vocabulary and words
# documents to words
for sentence in documents:
    print(word_tokenize(sentence))

['Emma', 'wakes', 'up', 'at', '7', 'AM', 'and', 'prepares', 'a', 'cup', 'of', 'coffee', 'before', 'heading', 'to', 'work', '.']
['The', 'weather', 'is', 'cloudy', 'today', ',', 'but', 'she', 'enjoys', 'the', 'cool', 'breeze', 'on', 'her', 'way', '.']
['At', 'the', 'office', ',', 'she', 'emails', 'her', 'manager', ':', "'Could", 'we', 'schedule', 'a', 'meeting', 'for', 'tomorrow', 'at', '10', 'AM', '?', "'"]
['Her', 'colleague', ',', 'Jake', ',', 'asks', ',', "'Do", 'you', 'need', 'help', 'with', 'the', 'report', '?', "'"]
['She', 'replies', ',', "'Yes", ',', 'that', 'would', 'be', 'great', '!', "'"]
['During', 'lunch', ',', 'she', 'reads', 'a', 'news', 'article', 'titled', "'New", 'AI', 'Breakthroughs', 'in', 'Healthcare', '.', "'"]
['Later', ',', 'her', 'phone', 'buzzes', 'with', 'a', 'notification', ':', "'Flash", 'Sale', '–', '50', '%', 'off', 'on', 'electronics', '!', "'"]
['After', 'work', ',', 'she', 'stops', 'by', 'the', 'grocery', 'store', 'to', 'buy', 'fresh', 'vegetables', 'a

In [12]:
#corpus to words:
words= word_tokenize(corpus)

In [13]:
words

['Emma',
 'wakes',
 'up',
 'at',
 '7',
 'AM',
 'and',
 'prepares',
 'a',
 'cup',
 'of',
 'coffee',
 'before',
 'heading',
 'to',
 'work',
 '.',
 'The',
 'weather',
 'is',
 'cloudy',
 'today',
 ',',
 'but',
 'she',
 'enjoys',
 'the',
 'cool',
 'breeze',
 'on',
 'her',
 'way',
 '.',
 'At',
 'the',
 'office',
 ',',
 'she',
 'emails',
 'her',
 'manager',
 ':',
 "'Could",
 'we',
 'schedule',
 'a',
 'meeting',
 'for',
 'tomorrow',
 'at',
 '10',
 'AM',
 '?',
 "'",
 'Her',
 'colleague',
 ',',
 'Jake',
 ',',
 'asks',
 ',',
 "'Do",
 'you',
 'need',
 'help',
 'with',
 'the',
 'report',
 '?',
 "'",
 'She',
 'replies',
 ',',
 "'Yes",
 ',',
 'that',
 'would',
 'be',
 'great',
 '!',
 "'",
 'During',
 'lunch',
 ',',
 'she',
 'reads',
 'a',
 'news',
 'article',
 'titled',
 "'New",
 'AI',
 'Breakthroughs',
 'in',
 'Healthcare',
 '.',
 "'",
 'Later',
 ',',
 'her',
 'phone',
 'buzzes',
 'with',
 'a',
 'notification',
 ':',
 "'Flash",
 'Sale',
 '–',
 '50',
 '%',
 'off',
 'on',
 'electronics',
 '!',
 "'",
 

In [14]:
#To split punctuation like 's as ' and s as words:
from nltk.tokenize import wordpunct_tokenize
words_punct = wordpunct_tokenize(corpus)
words_punct

['Emma',
 'wakes',
 'up',
 'at',
 '7',
 'AM',
 'and',
 'prepares',
 'a',
 'cup',
 'of',
 'coffee',
 'before',
 'heading',
 'to',
 'work',
 '.',
 'The',
 'weather',
 'is',
 'cloudy',
 'today',
 ',',
 'but',
 'she',
 'enjoys',
 'the',
 'cool',
 'breeze',
 'on',
 'her',
 'way',
 '.',
 'At',
 'the',
 'office',
 ',',
 'she',
 'emails',
 'her',
 'manager',
 ':',
 "'",
 'Could',
 'we',
 'schedule',
 'a',
 'meeting',
 'for',
 'tomorrow',
 'at',
 '10',
 'AM',
 "?'",
 'Her',
 'colleague',
 ',',
 'Jake',
 ',',
 'asks',
 ',',
 "'",
 'Do',
 'you',
 'need',
 'help',
 'with',
 'the',
 'report',
 "?'",
 'She',
 'replies',
 ',',
 "'",
 'Yes',
 ',',
 'that',
 'would',
 'be',
 'great',
 "!'",
 'During',
 'lunch',
 ',',
 'she',
 'reads',
 'a',
 'news',
 'article',
 'titled',
 "'",
 'New',
 'AI',
 'Breakthroughs',
 'in',
 'Healthcare',
 ".'",
 'Later',
 ',',
 'her',
 'phone',
 'buzzes',
 'with',
 'a',
 'notification',
 ':',
 "'",
 'Flash',
 'Sale',
 '–',
 '50',
 '%',
 'off',
 'on',
 'electronics',
 "!'",
 

In [15]:
#To tokenize words add . to the word itself except the last.
from nltk.tokenize import TreebankWordTokenizer
token_words = TreebankWordTokenizer()
tokenized_words=token_words.tokenize(corpus)

In [16]:
tokenized_words

['Emma',
 'wakes',
 'up',
 'at',
 '7',
 'AM',
 'and',
 'prepares',
 'a',
 'cup',
 'of',
 'coffee',
 'before',
 'heading',
 'to',
 'work.',
 'The',
 'weather',
 'is',
 'cloudy',
 'today',
 ',',
 'but',
 'she',
 'enjoys',
 'the',
 'cool',
 'breeze',
 'on',
 'her',
 'way.',
 'At',
 'the',
 'office',
 ',',
 'she',
 'emails',
 'her',
 'manager',
 ':',
 "'Could",
 'we',
 'schedule',
 'a',
 'meeting',
 'for',
 'tomorrow',
 'at',
 '10',
 'AM',
 '?',
 "'",
 'Her',
 'colleague',
 ',',
 'Jake',
 ',',
 'asks',
 ',',
 "'Do",
 'you',
 'need',
 'help',
 'with',
 'the',
 'report',
 '?',
 "'",
 'She',
 'replies',
 ',',
 "'Yes",
 ',',
 'that',
 'would',
 'be',
 'great',
 '!',
 "'",
 'During',
 'lunch',
 ',',
 'she',
 'reads',
 'a',
 'news',
 'article',
 'titled',
 "'New",
 'AI',
 'Breakthroughs',
 'in',
 'Healthcare.',
 "'",
 'Later',
 ',',
 'her',
 'phone',
 'buzzes',
 'with',
 'a',
 'notification',
 ':',
 "'Flash",
 'Sale',
 '–',
 '50',
 '%',
 'off',
 'on',
 'electronics',
 '!',
 "'",
 'After',
 'work

# STEMMING:

## 1. Porter Stemmer:

In [17]:
from nltk.stem import PorterStemmer

porter_stemming = PorterStemmer()

#applying porter stemming for each word:

for word in words:
    print(word+" ----> "+porter_stemming.stem(word))

Emma ----> emma
wakes ----> wake
up ----> up
at ----> at
7 ----> 7
AM ----> am
and ----> and
prepares ----> prepar
a ----> a
cup ----> cup
of ----> of
coffee ----> coffe
before ----> befor
heading ----> head
to ----> to
work ----> work
. ----> .
The ----> the
weather ----> weather
is ----> is
cloudy ----> cloudi
today ----> today
, ----> ,
but ----> but
she ----> she
enjoys ----> enjoy
the ----> the
cool ----> cool
breeze ----> breez
on ----> on
her ----> her
way ----> way
. ----> .
At ----> at
the ----> the
office ----> offic
, ----> ,
she ----> she
emails ----> email
her ----> her
manager ----> manag
: ----> :
'Could ----> 'could
we ----> we
schedule ----> schedul
a ----> a
meeting ----> meet
for ----> for
tomorrow ----> tomorrow
at ----> at
10 ----> 10
AM ----> am
? ----> ?
' ----> '
Her ----> her
colleague ----> colleagu
, ----> ,
Jake ----> jake
, ----> ,
asks ----> ask
, ----> ,
'Do ----> 'do
you ----> you
need ----> need
help ----> help
with ----> with
the ----> the
report ---->

## 2. Regular expression stemmer ( RegexpStemmer)

In [18]:
from nltk.stem import RegexpStemmer
#it takes regular expression and removes prefix and suffix that matches.
reg_stemmer = RegexpStemmer('ing$|s$|tion$|ary$|able$', min=4)

#applying Regular expression stemming for each word:

for word in words_punct:
    print(word+" ----> "+reg_stemmer.stem(word))

Emma ----> Emma
wakes ----> wake
up ----> up
at ----> at
7 ----> 7
AM ----> AM
and ----> and
prepares ----> prepare
a ----> a
cup ----> cup
of ----> of
coffee ----> coffee
before ----> before
heading ----> head
to ----> to
work ----> work
. ----> .
The ----> The
weather ----> weather
is ----> is
cloudy ----> cloudy
today ----> today
, ----> ,
but ----> but
she ----> she
enjoys ----> enjoy
the ----> the
cool ----> cool
breeze ----> breeze
on ----> on
her ----> her
way ----> way
. ----> .
At ----> At
the ----> the
office ----> office
, ----> ,
she ----> she
emails ----> email
her ----> her
manager ----> manager
: ----> :
' ----> '
Could ----> Could
we ----> we
schedule ----> schedule
a ----> a
meeting ----> meet
for ----> for
tomorrow ----> tomorrow
at ----> at
10 ----> 10
AM ----> AM
?' ----> ?'
Her ----> Her
colleague ----> colleague
, ----> ,
Jake ----> Jake
, ----> ,
asks ----> ask
, ----> ,
' ----> '
Do ----> Do
you ----> you
need ----> need
help ----> help
with ----> with
the ---->

## 3. Snowball Stemmer:

In [19]:
from nltk.stem import SnowballStemmer

#function intialization:
snowball_stem = SnowballStemmer('english')

#applying snowball expression stemming for each word:

for word in words_punct:
    print(word+" ----> "+snowball_stem.stem(word))

Emma ----> emma
wakes ----> wake
up ----> up
at ----> at
7 ----> 7
AM ----> am
and ----> and
prepares ----> prepar
a ----> a
cup ----> cup
of ----> of
coffee ----> coffe
before ----> befor
heading ----> head
to ----> to
work ----> work
. ----> .
The ----> the
weather ----> weather
is ----> is
cloudy ----> cloudi
today ----> today
, ----> ,
but ----> but
she ----> she
enjoys ----> enjoy
the ----> the
cool ----> cool
breeze ----> breez
on ----> on
her ----> her
way ----> way
. ----> .
At ----> at
the ----> the
office ----> offic
, ----> ,
she ----> she
emails ----> email
her ----> her
manager ----> manag
: ----> :
' ----> '
Could ----> could
we ----> we
schedule ----> schedul
a ----> a
meeting ----> meet
for ----> for
tomorrow ----> tomorrow
at ----> at
10 ----> 10
AM ----> am
?' ----> ?'
Her ----> her
colleague ----> colleagu
, ----> ,
Jake ----> jake
, ----> ,
asks ----> ask
, ----> ,
' ----> '
Do ----> do
you ----> you
need ----> need
help ----> help
with ----> with
the ----> the
repo

# LEMMATIZATION:

In [20]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [21]:
#to prevent the loss of meaning - we use lemmatization. and output is called lemma.
from nltk.stem import WordNetLemmatizer

lemmatizer_func = WordNetLemmatizer()
for word in words_punct:
    print(word+" ----> "+" 1.Noun: "+lemmatizer_func.lemmatize(word, pos='n')+" 2.Verb: "+lemmatizer_func.lemmatize(word, pos='v')+" 3.Adjective: "+lemmatizer_func.lemmatize(word, pos='a')+" 4.Adverb: "+lemmatizer_func.lemmatize(word, pos='r')+" 5.Satellite Adjective: "+lemmatizer_func.lemmatize(word, pos='s'))
    


Emma ---->  1.Noun: Emma 2.Verb: Emma 3.Adjective: Emma 4.Adverb: Emma 5.Satellite Adjective: Emma
wakes ---->  1.Noun: wake 2.Verb: wake 3.Adjective: wakes 4.Adverb: wakes 5.Satellite Adjective: wakes
up ---->  1.Noun: up 2.Verb: up 3.Adjective: up 4.Adverb: up 5.Satellite Adjective: up
at ---->  1.Noun: at 2.Verb: at 3.Adjective: at 4.Adverb: at 5.Satellite Adjective: at
7 ---->  1.Noun: 7 2.Verb: 7 3.Adjective: 7 4.Adverb: 7 5.Satellite Adjective: 7
AM ---->  1.Noun: AM 2.Verb: AM 3.Adjective: AM 4.Adverb: AM 5.Satellite Adjective: AM
and ---->  1.Noun: and 2.Verb: and 3.Adjective: and 4.Adverb: and 5.Satellite Adjective: and
prepares ---->  1.Noun: prepares 2.Verb: prepare 3.Adjective: prepares 4.Adverb: prepares 5.Satellite Adjective: prepares
a ---->  1.Noun: a 2.Verb: a 3.Adjective: a 4.Adverb: a 5.Satellite Adjective: a
cup ---->  1.Noun: cup 2.Verb: cup 3.Adjective: cup 4.Adverb: cup 5.Satellite Adjective: cup
of ---->  1.Noun: of 2.Verb: of 3.Adjective: of 4.Adverb: of 5.Sate

# STOPWORDS:

In [22]:
#stemming along with stopwords:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
#to remove unnecessary words

nltk.download('stopwords')
#This downloads this package into particular location to use

stopwords.words('english')
#it returns all stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [23]:
#Stopwords removal-using PorterStemmer:

In [24]:
for i in range(len(sentences)):
    words_bfr_stpwrds = nltk.word_tokenize(sentences[i])
    #index of words
    #applying stopwords: (using list comprehension)
    words_aftr_stpwrds=[porter_stemming.stem(wrd) for wrd in words_bfr_stpwrds if wrd not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words_aftr_stpwrds)



In [25]:
sentences

['emma wake 7 am prepar cup coffe head work .',
 'the weather cloudi today , enjoy cool breez way .',
 "at offic , email manag : 'could schedul meet tomorrow 10 am ? '",
 "her colleagu , jake , ask , 'do need help report ? '",
 "she repli , 'ye , would great ! '",
 "dure lunch , read news articl titl 'new ai breakthrough healthcar . '",
 "later , phone buzz notif : 'flash sale – 50 % electron ! '",
 'after work , stop groceri store buy fresh veget bread .',
 'at home , watch documentari wildlif conserv .',
 'befor sleep , set alarm 6 am plan task next day .']

In [26]:
#Stopwords removal-using Snowball Stemmer:

In [27]:
for i in range(len(documents)):
    words_bfr_stpwrds = nltk.word_tokenize(documents[i])
    #index of words
    #applying stopwords: (using list comprehension)
    words_aftr_stpwrds=[snowball_stem.stem(wrd) for wrd in words_bfr_stpwrds if wrd not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words_aftr_stpwrds)



In [28]:
sentences

['emma wake 7 am prepar cup coffe head work .',
 'the weather cloudi today , enjoy cool breez way .',
 "at offic , email manag : could schedul meet tomorrow 10 am ? '",
 "her colleagu , jake , ask , do need help report ? '",
 "she repli , yes , would great ! '",
 "dure lunch , read news articl titl new ai breakthrough healthcar . '",
 "later , phone buzz notif : flash sale – 50 % electron ! '",
 'after work , stop groceri store buy fresh veget bread .',
 'at home , watch documentari wildlif conserv .',
 'befor sleep , set alarm 6 am plan task next day .']

In [29]:
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [30]:
#Stopwords removal-using Lemmatization:
for i in range(len(documents)):
    words_bfr_stpwrds = nltk.word_tokenize(documents[i])
    #index of words
    non_stp_words = [wrd for wrd in words_bfr_stpwrds if wrd not in set(stopwords.words('english'))]
    #to get a list of all words other than stopwords
    pos_tag = nltk.pos_tag(non_stp_words)
    print(pos_tag)
    #This prints the post tag of the word.
    
    #applying stopwords: (using list comprehension)
    words_aftr_stpwrds=[lemmatizer_func.lemmatize(wrd, pos='v') for wrd in words_bfr_stpwrds if wrd not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words_aftr_stpwrds)


[('Emma', 'NNP'), ('wakes', 'VBZ'), ('7', 'CD'), ('AM', 'NNP'), ('prepares', 'NNS'), ('cup', 'VBP'), ('coffee', 'NN'), ('heading', 'NN'), ('work', 'NN'), ('.', '.')]
[('The', 'DT'), ('weather', 'NN'), ('cloudy', 'NN'), ('today', 'NN'), (',', ','), ('enjoys', 'VBZ'), ('cool', 'JJ'), ('breeze', 'NN'), ('way', 'NN'), ('.', '.')]
[('At', 'IN'), ('office', 'NN'), (',', ','), ('emails', 'VBZ'), ('manager', 'NN'), (':', ':'), ("'Could", 'MD'), ('schedule', 'VB'), ('meeting', 'NN'), ('tomorrow', 'NN'), ('10', 'CD'), ('AM', 'NNP'), ('?', '.'), ("'", "''")]
[('Her', 'PRP$'), ('colleague', 'NN'), (',', ','), ('Jake', 'NNP'), (',', ','), ('asks', 'VBZ'), (',', ','), ("'Do", "''"), ('need', 'VBP'), ('help', 'VB'), ('report', 'VB'), ('?', '.'), ("'", "''")]
[('She', 'PRP'), ('replies', 'VBZ'), (',', ','), ("'Yes", "''"), (',', ','), ('would', 'MD'), ('great', 'JJ'), ('!', '.'), ("'", "''")]
[('During', 'IN'), ('lunch', 'NN'), (',', ','), ('reads', 'VBZ'), ('news', 'NN'), ('article', 'NN'), ('titled'

In [31]:
sentences

['Emma wake 7 AM prepare cup coffee head work .',
 'The weather cloudy today , enjoy cool breeze way .',
 "At office , email manager : 'Could schedule meet tomorrow 10 AM ? '",
 "Her colleague , Jake , ask , 'Do need help report ? '",
 "She reply , 'Yes , would great ! '",
 "During lunch , read news article title 'New AI Breakthroughs Healthcare . '",
 "Later , phone buzz notification : 'Flash Sale – 50 % electronics ! '",
 'After work , stop grocery store buy fresh vegetables bread .',
 'At home , watch documentary wildlife conservation .',
 'Before sleep , set alarm 6 AM plan task next day .']

### NAMED ENTITY RECOGNITION

In [32]:
#This gives a graph-like figure for words and their post tags. 

In [33]:
pos_tags = nltk.pos_tag(words_punct)
pos_tags

[('Emma', 'NNP'),
 ('wakes', 'VBZ'),
 ('up', 'RP'),
 ('at', 'IN'),
 ('7', 'CD'),
 ('AM', 'NNP'),
 ('and', 'CC'),
 ('prepares', 'VBZ'),
 ('a', 'DT'),
 ('cup', 'NN'),
 ('of', 'IN'),
 ('coffee', 'NN'),
 ('before', 'IN'),
 ('heading', 'VBG'),
 ('to', 'TO'),
 ('work', 'VB'),
 ('.', '.'),
 ('The', 'DT'),
 ('weather', 'NN'),
 ('is', 'VBZ'),
 ('cloudy', 'VBN'),
 ('today', 'NN'),
 (',', ','),
 ('but', 'CC'),
 ('she', 'PRP'),
 ('enjoys', 'VBZ'),
 ('the', 'DT'),
 ('cool', 'JJ'),
 ('breeze', 'NN'),
 ('on', 'IN'),
 ('her', 'PRP$'),
 ('way', 'NN'),
 ('.', '.'),
 ('At', 'IN'),
 ('the', 'DT'),
 ('office', 'NN'),
 (',', ','),
 ('she', 'PRP'),
 ('emails', 'VBZ'),
 ('her', 'PRP$'),
 ('manager', 'NN'),
 (':', ':'),
 ("'", 'POS'),
 ('Could', 'MD'),
 ('we', 'PRP'),
 ('schedule', 'VB'),
 ('a', 'DT'),
 ('meeting', 'NN'),
 ('for', 'IN'),
 ('tomorrow', 'NN'),
 ('at', 'IN'),
 ('10', 'CD'),
 ('AM', 'NNP'),
 ("?'", 'NNP'),
 ('Her', 'NNP'),
 ('colleague', 'NN'),
 (',', ','),
 ('Jake', 'NNP'),
 (',', ','),
 ('asks',

In [34]:
nltk.download('maxent_ne_chunker')
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [35]:
nltk.ne_chunk(pos_tags).draw()

2025-02-03 10:11:03.144 python[4000:33855] +[IMKClient subclass]: chose IMKClient_Legacy
2025-02-03 10:11:03.144 python[4000:33855] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


# TEXT PROCESSING ----- STEP 2 -----> CONVERTING TEXT TO VECTORS:

In [36]:
import pandas as pd
messages = pd.read_csv('email.csv', names=["label", "message"])

In [37]:
messages=messages.drop(0)

In [38]:
messages

label                                            message
1                ham  Go until jurong point, crazy.. Available only ...
2                ham                      Ok lar... Joking wif u oni...
3               spam  Free entry in 2 a wkly comp to win FA Cup fina...
4                ham  U dun say so early hor... U c already then say...
5                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5569             ham               Will ü b going to esplanade fr home?
5570             ham  Pity, * was in mood for that. So...any other s...
5571             ham  The guy did some bitching but I acted like i'd...
5572             ham                         Rofl. Its true to its name
5573  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

##### Data Cleaning & preprocessing:

In [39]:
import re
import nltk

nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pravallika/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [40]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

#Intializing stemmer function:
ps = PorterStemmer()

#List to save cleaned data
corpus=[]

for i in range(1, len(messages)):
    review = re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review.lower()
    #list conversion
    review=review.split()
    #stemming:
    review = [ps.stem(wrd) for wrd in review if wrd not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [41]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate t c appli',
 'u dun say earli hor u c alreadi say',
 'nah i think goe usf live around though',
 'freemsg hey darl week word back i like fun still tb ok xxx std chg send rcv',
 'even brother like speak they treat like aid patent',
 'as per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner as valu network custom select receivea prize reward to claim call claim code kl valid hour',
 'had mobil month u r entitl updat latest colour mobil camera free call the mobil updat co free',
 'i gonna home soon want talk stuff anymor tonight k i cri enough today',
 'six chanc win cash from pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent you week free membership prize jackpot txt word claim no t c www dbuk net lccltd pobo

In [42]:
#Doing lemmatization for more accuaracy:
#Intializing lemmatizer function:
lemm = WordNetLemmatizer()

#List to save cleaned data
corpus=[]

for i in range(1, len(messages)):
    review = re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review.lower()
    #list conversion
    review=review.split()
    #lemmatization:
    review = [lemm.lemmatize(wrd, pos='v') for wrd in review if wrd not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [43]:
corpus

['Go jurong point crazy Available bugis n great world la e buffet Cine get amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf live around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friends Callertune',
 'WINNER As value network customer select receivea prize reward To claim call Claim code KL Valid hours',
 'Had mobile months U R entitle Update latest colour mobiles camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cry enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day days TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word C

### 1. ONE HOT ENCODING(OHE)


In [44]:
import sklearn
from sklearn.preprocessing import MultiLabelBinarizer
ohe = MultiLabelBinarizer()

In [45]:
ohe

MultiLabelBinarizer()

In [46]:
X = ohe.fit_transform(corpus)

In [47]:
X

array([[1, 1, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [48]:
X.shape

(5572, 58)

In [49]:
df_ohe = pd.DataFrame(X, columns=ohe.classes_)

In [50]:
df_ohe

A  B  C  D  E  F  G  H  I  ...  q  r  s  t  u  v  w  x  y  z
0     1  1  0  1  0  0  0  1  0  0  ...  0  1  1  1  1  1  1  0  1  1
1     1  0  0  0  0  0  0  0  0  0  ...  0  1  0  0  1  0  1  0  0  0
2     1  1  0  1  0  0  1  0  0  0  ...  1  1  1  1  1  1  1  1  1  0
3     1  0  0  0  0  0  0  0  0  0  ...  0  1  1  0  1  0  0  0  1  0
4     1  0  0  0  0  0  0  0  0  1  ...  0  1  1  1  1  1  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
5567  1  0  1  0  0  0  0  0  0  0  ...  0  1  1  1  1  0  0  0  1  1
5568  1  0  0  0  0  0  0  0  0  0  ...  0  1  1  0  0  0  0  0  0  0
5569  1  0  0  0  0  0  0  0  0  0  ...  0  0  1  1  1  0  0  0  1  0
5570  1  0  0  0  0  0  0  0  0  1  ...  0  1  1  1  1  1  1  1  1  0
5571  1  0  0  0  0  0  0  0  0  1  ...  0  1  1  1  1  0  0  0  0  0

[5572 rows x 58 columns]

### 2. BAG OF WORDS(BOW)

In [51]:
#converting from text to vectors:
from sklearn.feature_extraction.text import CountVectorizer

#intializing
cv = CountVectorizer(binary=True,max_features=2500)
#applying bow


In [52]:
cv

CountVectorizer(binary=True, max_features=2500)

In [53]:
#applying bow function to datset to convert text to vector

X = cv.fit_transform(corpus).toarray()

X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
X.shape

(5572, 2500)

In [55]:
cv.vocabulary_
#gives the frequency of the word

{'go': 829,
 'point': 1576,
 'crazy': 459,
 'available': 148,
 'bugis': 282,
 'great': 850,
 'world': 2433,
 'la': 1107,
 'cine': 380,
 'get': 816,
 'wat': 2337,
 'ok': 1461,
 'lar': 1116,
 'wif': 2389,
 'oni': 1472,
 'free': 762,
 'entry': 629,
 'wkly': 2420,
 'comp': 413,
 'win': 2395,
 'cup': 471,
 'final': 716,
 'tkts': 2175,
 'st': 1997,
 'may': 1270,
 'text': 2121,
 'receive': 1685,
 'question': 1647,
 'std': 2009,
 'txt': 2232,
 'rate': 1665,
 'apply': 106,
 'dun': 593,
 'say': 1804,
 'early': 598,
 'already': 70,
 'nah': 1390,
 'think': 2146,
 'usf': 2277,
 'live': 1178,
 'around': 123,
 'though': 2154,
 'freemsg': 764,
 'hey': 910,
 'darling': 492,
 'week': 2354,
 'word': 2430,
 'back': 163,
 'like': 1161,
 'fun': 786,
 'still': 2013,
 'tb': 2097,
 'xxx': 2459,
 'send': 1830,
 'rcv': 1668,
 'even': 643,
 'brother': 273,
 'speak': 1981,
 'they': 2143,
 'treat': 2212,
 'as': 129,
 'per': 1529,
 'request': 1722,
 'melle': 1287,
 'oru': 1491,
 'minnaminunginte': 1309,
 'nurungu': 

#### 3. N-Grams:

In [56]:
cv_ngrams = CountVectorizer(binary=True,max_features=2500, ngram_range=(1, 3))

In [57]:
cv_ngrams

CountVectorizer(binary=True, max_features=2500, ngram_range=(1, 3))

In [58]:
X = cv_ngrams.fit_transform(corpus).toarray()

In [59]:
cv_ngrams.vocabulary_

{'go': 781,
 'point': 1590,
 'crazy': 443,
 'available': 114,
 'bugis': 225,
 'great': 817,
 'world': 2423,
 'la': 1082,
 'cine': 344,
 'get': 753,
 'wat': 2301,
 'ok': 1446,
 'lar': 1096,
 'wif': 2373,
 'free': 709,
 'entry': 610,
 'wkly': 2408,
 'comp': 398,
 'win': 2380,
 'cup': 456,
 'final': 680,
 'st': 1935,
 'may': 1253,
 'text': 2032,
 'receive': 1683,
 'question': 1651,
 'std': 1947,
 'txt': 2162,
 'rate': 1665,
 'apply': 70,
 'free entry': 714,
 'entry wkly': 613,
 'txt rate': 2167,
 'rate apply': 1666,
 'txt rate apply': 2168,
 'dun': 571,
 'say': 1775,
 'early': 578,
 'already': 42,
 'nah': 1353,
 'think': 2068,
 'usf': 2249,
 'live': 1166,
 'around': 82,
 'though': 2085,
 'think go': 2070,
 'freemsg': 719,
 'hey': 897,
 'week': 2326,
 'word': 2418,
 'back': 138,
 'like': 1153,
 'fun': 737,
 'still': 1948,
 'xxx': 2455,
 'send': 1814,
 'even': 621,
 'brother': 218,
 'speak': 1923,
 'they': 2065,
 'treat': 2143,
 'as': 89,
 'per': 1512,
 'request': 1717,
 'set': 1837,
 'pres

In [60]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [61]:
X.shape

(5572, 2500)

#### 4. TF-IDF:

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=200)

In [63]:
tfidf

TfidfVectorizer(max_features=200)

In [64]:
X = tfidf.fit_transform(corpus).toarray()

In [65]:
tfidf.vocabulary_

{'go': 51,
 'great': 54,
 'get': 49,
 'wat': 180,
 'ok': 118,
 'free': 46,
 'win': 189,
 'st': 147,
 'text': 155,
 'txt': 171,
 'dun': 36,
 'say': 132,
 'already': 0,
 'think': 162,
 'live': 84,
 'around': 7,
 'hey': 63,
 'week': 184,
 'word': 191,
 'back': 11,
 'like': 83,
 'still': 149,
 'send': 134,
 'even': 39,
 'per': 120,
 'friends': 48,
 'customer': 29,
 'prize': 128,
 'to': 165,
 'claim': 22,
 'call': 15,
 'mobile': 100,
 'the': 158,
 'co': 23,
 'gonna': 52,
 'home': 65,
 'soon': 144,
 'want': 179,
 'talk': 153,
 'tonight': 169,
 'today': 166,
 'cash': 19,
 'day': 31,
 'reply': 130,
 'urgent': 174,
 'you': 198,
 'no': 112,
 'www': 194,
 'right': 131,
 'thank': 156,
 'take': 152,
 'help': 62,
 'time': 164,
 'have': 59,
 'will': 188,
 'use': 176,
 'next': 109,
 'message': 96,
 'com': 24,
 'oh': 117,
 'watch': 181,
 'name': 106,
 'yes': 197,
 'he': 60,
 'make': 91,
 'way': 182,
 'feel': 41,
 'that': 157,
 'dont': 35,
 'miss': 99,
 'ur': 173,
 'try': 170,
 'is': 71,
 'so': 141,
 'f

In [66]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
#tfidf and ngram:
tfidf_ngram = TfidfVectorizer(max_features=200, ngram_range=(1, 3))

In [68]:
tfidf_ngram

TfidfVectorizer(max_features=200, ngram_range=(1, 3))

In [69]:
X = tfidf_ngram.fit_transform(corpus).toarray()

In [70]:
tfidf_ngram.vocabulary_

{'go': 50,
 'great': 53,
 'get': 48,
 'wat': 180,
 'ok': 118,
 'free': 46,
 'win': 189,
 'st': 147,
 'text': 155,
 'txt': 171,
 'dun': 36,
 'say': 133,
 'already': 0,
 'think': 162,
 'live': 83,
 'around': 7,
 'hey': 62,
 'week': 184,
 'word': 191,
 'back': 11,
 'like': 82,
 'still': 149,
 'send': 135,
 'even': 39,
 'per': 120,
 'friends': 47,
 'customer': 29,
 'prize': 129,
 'to': 165,
 'claim': 22,
 'call': 15,
 'mobile': 100,
 'the': 158,
 'co': 23,
 'gonna': 51,
 'home': 64,
 'soon': 145,
 'want': 179,
 'talk': 153,
 'tonight': 169,
 'today': 166,
 'cash': 19,
 'day': 31,
 'reply': 131,
 'urgent': 174,
 'you': 198,
 'no': 112,
 'www': 194,
 'right': 132,
 'thank': 156,
 'take': 152,
 'help': 61,
 'time': 164,
 'have': 58,
 'will': 188,
 'use': 176,
 'next': 109,
 'message': 96,
 'com': 24,
 'oh': 117,
 'watch': 181,
 'name': 106,
 'yes': 197,
 'he': 59,
 'make': 91,
 'way': 182,
 'feel': 41,
 'that': 157,
 'dont': 35,
 'miss': 99,
 'ur': 173,
 'try': 170,
 'is': 70,
 'so': 142,
 'f

In [71]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [72]:
X.shape

(5572, 200)

# TEXT PROCESSING ----- STEP 3 -----> CONVERTING TEXT TO VECTORS:

### 1. Word2Vec:

In [73]:
!pip show gensim

Name: gensim
Version: 4.3.3
Summary: Python framework for fast Vector Space Modelling
Home-page: https://radimrehurek.com/gensim/
Author: Radim Rehurek
Author-email: me@radimrehurek.com
License: LGPL-2.1-only
Location: /opt/anaconda3/lib/python3.12/site-packages
Requires: numpy, scipy, smart-open
Required-by: 


In [74]:
import gensim

In [76]:
from gensim.models import Word2Vec, KeyedVectors

import gensim.downloader as api

In [78]:
word_vec_model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [101]:
word_vec_model.save("word2vec_model.model")

In [80]:
#getting vector for specific words:
vec_king = word_vec_model['King']
vec_prince = word_vec_model['Prince']

In [81]:
vec_king

array([-0.00350952,  0.01623535, -0.08154297,  0.12792969,  0.11230469,
       -0.00534058,  0.03063965,  0.04931641,  0.22070312,  0.07373047,
       -0.13769531,  0.16210938,  0.02148438, -0.09375   , -0.12792969,
       -0.12402344, -0.11132812,  0.11816406, -0.07861328,  0.25390625,
        0.01794434,  0.14160156,  0.0612793 , -0.08691406,  0.07763672,
        0.05175781, -0.24609375, -0.17578125,  0.14746094,  0.06640625,
       -0.03833008, -0.09033203, -0.07226562,  0.09375   , -0.18847656,
        0.06347656,  0.24121094,  0.00714111, -0.30273438, -0.02478027,
       -0.09619141, -0.30859375, -0.06054688,  0.22167969,  0.07763672,
        0.05834961,  0.15527344, -0.13476562, -0.00341797, -0.13964844,
       -0.02905273,  0.03833008, -0.15332031, -0.20996094,  0.21679688,
        0.01171875, -0.078125  ,  0.00402832, -0.23535156, -0.10400391,
        0.08837891,  0.25976562,  0.02709961,  0.01123047,  0.12988281,
       -0.11914062, -0.07861328, -0.04736328, -0.06591797,  0.07

In [82]:
vec_king.shape

(300,)

In [83]:
vec_prince

array([ 0.00549316,  0.10302734, -0.17089844, -0.18847656,  0.01879883,
        0.0703125 , -0.16796875, -0.11962891, -0.10302734, -0.01416016,
        0.04003906,  0.20703125,  0.04052734, -0.09570312, -0.34765625,
       -0.17578125, -0.0039978 , -0.08935547,  0.13183594,  0.3125    ,
        0.06030273, -0.14257812,  0.15722656, -0.01342773,  0.07470703,
        0.10498047, -0.33789062, -0.06835938,  0.21582031, -0.11669922,
        0.08447266,  0.07568359, -0.140625  ,  0.02185059, -0.11572266,
       -0.01031494,  0.11035156, -0.03930664, -0.38671875,  0.11767578,
       -0.15820312, -0.16992188, -0.1484375 ,  0.11816406,  0.17871094,
       -0.02490234,  0.24707031, -0.39257812, -0.05395508, -0.0612793 ,
        0.10791016,  0.08349609, -0.08007812, -0.27539062,  0.15429688,
       -0.0378418 , -0.36132812, -0.07324219, -0.24511719, -0.3515625 ,
        0.17578125,  0.30273438,  0.13769531, -0.04418945, -0.19921875,
       -0.00415039, -0.15039062, -0.09570312,  0.12255859,  0.10

In [84]:
vec_prince.shape

(300,)

In [85]:
word_vec_model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [86]:
word_vec_model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [87]:
word_vec_model.most_similar('King')

[('Jackson', 0.5326348543167114),
 ('Prince', 0.5306329727172852),
 ('Tupou_V.', 0.5292826294898987),
 ('KIng', 0.5227501392364502),
 ('e_mail_robert.king_@', 0.5173623561859131),
 ('king', 0.5158917903900146),
 ('Queen', 0.5157250165939331),
 ('Geoffrey_Rush_Exit', 0.49920955300331116),
 ('prosecutor_Dan_Satterberg', 0.49850785732269287),
 ('NECN_Alison', 0.49128594994544983)]

In [88]:
word_vec_model.similarity("king", "queen")

0.6510957

In [89]:
word_vec_model.similarity("king", "prince")

0.61599934

In [90]:
word_vec_model.similarity("king", "man")

0.22942673

In [91]:
word_vec_model.similarity("woman", "queen")

0.31618136

In [92]:
word_vec_model.similarity("hockey", "sports")

0.53541523

In [93]:
#arithmetic operations on vectors:
vec = word_vec_model['king']-word_vec_model['man']+word_vec_model['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [94]:
#to find text for vector:
word_vec_model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]